#!/bin/bash

#$ -pe smp 32                       # Specify parallel environment and core size
#$ -M tma2@nd.edu                   # Email address for job notification
#$ -m abe                           # Send mail when job begins, ends, and aborts
#$ -q gpu@@yye7_lab                 # Run on the GPU cluster
#$ -o ~/Github/HGTab/Logs/system/dpr_wikisql_test.log  # Standard output log file
#$ -l gpu_card=4                    # Request 4 GPU cards
#$ -N wikisql_test              # Specify job name

conda activate llm
cd ~/Github/HGTab
python src/main.py configs/wikisql/hg_wikisql.jsonnet --accelerator gpu --devices 4 --strategy ddp --experiment_name DPR_large_on_WikiSQL_with_in_batch_over_hypergraph --mode test --test_evaluation_name original_sets --opts test.batch_size=32
